version: "3.7"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


  producer:
    build:
      context: ./services
      dockerfile: Dockerfile
    image: kafka-fastapi:latest
    depends_on:
      - zookeeper
      - kafka
    command: uvicorn app.main:app --workers 1 --reload --host 0.0.0.0 --port 8000
    env_file:
      - ./services/producer/.env
    volumes:
      - ./services/producer/:/usr/src/app
    ports:
      - "8001:8000"

  consumer:
    image: kafka-fastapi:latest
    depends_on:
      - zookeeper
      - kafka
    command: uvicorn app.main:app --workers 1 --reload --host 0.0.0.0 --port 8000
    env_file:
      - ./services/producer/.env
    volumes:
      - ./services/consumer/:/usr/src/app
    ports:
        - "8002:8000"
